# Generated by Django 3.1.5 on 2021-07-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
