# Generated by Django 3.1.5 on 2021-07-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPi', '0003_auto_20210707_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
