# Generated by Django 3.1.5 on 2021-07-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPi', '0005_auto_20210707_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
